# ==============================================================
# WAX CONFIGURATION
# ==============================================================
# Jekyll configuration files are written in YAML format.
# Colons, tabs/spacing, and quotes are meaningful in YAML.
# It is recommended you look at the following guide to avoid
# syntax errors in this file:
# ~> https://learnxinyminutes.com/docs/yaml/
#
#
# Questions ?
# ~> https://minicomp.github.io/wiki/#/
#
# ---------------------------------------------------------------
# MAIN SETTINGS
# ---------------------------------------------------------------
# Feel free to change these! For more info, refer to:
# ~> https://jekyllrb.com/docs/configuration/options/

title:            'Medieval Fragments at Cornell'
description:      'A minimal collections exhibit platform'
url:              'https://kam535.github.io'
baseurl:          '/medieval-fragments'
copyright:        'Cornell University Digital CoLab, 2024'
logo:             '/img/book.png'
default_thumb:    '/img/default.png'
metadata: 'medievalfragments'

# ---------------------------------------------------------------
# BUILD SETTINGS
# ---------------------------------------------------------------
# Best not to mess with these unless you know what you're doing!

permalink: 'pretty'
sass:
  style: compressed
exclude: ["Gemfile*", "*.gemspec", "Rakefile", "vendor", "spec", "README.md", "LICENSE.txt", "Docker*"]
webrick:
  headers:
    'Access-Control-Allow-Origin': '*'
kramdown:
 auto_ids:       true
 footnote_nr:    1
 entity_output:  as_char
 footnote_backlink: "&#x21a9;&#xfe0e;"
 toc_levels:     1..6
 smart_quotes:   lsquo,rsquo,ldquo,rdquo
 enable_coderay: false


# --------------------------------------------------------------
# COLLECTION SETTINGS
# --------------------------------------------------------------
# Wax leverages Jekyll collections for much of its
# functionality, therefor some of the keys below are from
# Jekyll while others are Wax-specific.
# For more info, refer to:
# ~> https://jekyllrb.com/docs/collections/

plugins:
  - jekyll-lunr-js-custom-search
  
# --------------------------------------------------------------
# SEARCH INDEX SETTINGS
# --------------------------------------------------------------
# You can create multiple search indexes below (though only one is
# recommended!) by specifying
# an `index` file to write it to and some `collections` for it to index
# and running `$ bundle exec rake wax:search` .

lunr_settings:
  atozsortfield: preferredName
  collections: [people]
  displayfields:
  - {field: preferredName, headerfield: true, highlight: false}
  - {field: imagesrc, headerimage: true, highlight: false}
  - {field: variantNames, label: Variant Name}
  - {field: occupation, joiner: '; ', label: Occupation, truncate: 2}
  - {field: born, label: Birth Year}
  - {field: ethnicity, label: Ethnicity, plural: Ethnicities}
  - {conditional: 'True', field: works, joiner: '; ', label: Work}
  fields:
  - boost: 10
    facetfield: true
    jekyllfields: [ethnicity]
    searchfield: ethnicity
  - boost: 10
    jekyllfields: [preferredName, variantNames]
    searchfield: name
  - boost: 10
    facetfield: true
    jekyllfields: [occupation]
    searchfield: occupation
  - boost: 1
    jekyllfields: [content]
    searchfield: description
  - boost: 1
    jekyllfields: [contributions]
    searchfield: contributor
    widget: flatten
  - boost: 10
    facetfield: true
    jekyllfields: [wlCity]
    parentfield: workLocations
    searchfield: cities
    widget: nested
  - boost: 10
    facetfield: true
    jekyllfields: [wlCountry]
    parentfield: workLocations
    searchfield: countries
    widget: nested
  - boost: 10
    collection: works
    jekyllfields: [preferredName, variantName]
    matchfield: contributor
    searchfield: works
    secondaryfield: contributorId
    widget: relational
  fuzzysearchfields: [name, birthplace, residences, worklocations]
  view_facets: 5

search:
  main:
    index: '/search/index.json' # file the index will get written to
    collections:
      medievalfragments:
        content: false # whether or not to index page content
        fields: # the metadata fields to index
          - label
          - agent
          - dateStart
          - dateEnd
          - recnum
          - catalogrecord
          - collectionnum
          - worktype
          - tTags
          - archcoll
          - box
          - folder
          - rights
          - bibliography
          - originalwork

collections:
  exhibits:
    output: true
  medievalfragments: # name of collection
    output: true # makes sure pages are output as html files
    layout: 'medfrag_item' # the layout for the pages to use
    permalink: '/medievalfragments/:path'
    metadata:
      source: 'medievalfragments.csv' # path to the metadata file within `_data`
    images:
      source: 'raw_images/medfragments' # path to the directory of images within `_data`
  medievalwholes:
    output: true
    layout: 'medfrag_item'
    metadata:
      source: 'medievalwholes.csv'
    images:
      source: 'raw_images/medwholes'
# --------------------------------------------------------------
# SITE MENU SETTINGS
# --------------------------------------------------------------
# Each menu item needs a `label` (whats shown), and a `link`
# (where it goes). An item can optionally have a dropdown
# submenu via `sub`.

menu:
  - label: 'Browse'
    link: '/collection/'
  - label: 'Search'
    link: '/search/'
  - label: 'Teaching Tools'
    link: '/teaching-tools/'
  - label: 'Timeline'
    link: '/timeline/'
  - label: 'Map'
    link: '/map.html'
  - label: 'Data'
    link: '/data/'
  - label: 'Deep Search'
    link: '/deep-search/'
  - label: 'Exhibits'
    sub:
      - label: 'Bonaventure Lyffe of Chryste'
        link: '/exhibits/a/'
      - label: 'Parchment fragments'
        link: '/exhibits/b/'
      - label: 'Sample Exhibit Shell'
        link: '/exhibits/c/'
  - label: 'About'
    link: '/about/'
 



# --------------------------------------------------------------
# SITE FOOTER SETTINGS
# --------------------------------------------------------------
#

footer:
  links:
    - label: 'GitHub'
      link: 'https://github.com/kam535/waxbuilder'
    - label: 'Credits'
      link: '/credits'
    - label: 'Wax Wiki'
      link: 'https://minicomp.github.io/wiki/wax/'
  logos:
    - img: '/img/book.png'

# FIN
